name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # or whatever version your project uses

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build dotNetExpress/dotnetExpress.csproj --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack dotNetExpress/dotnetExpress.csproj --configuration Release --no-build --output ./nupkg

    - name: Push to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
